# generated by datamodel-codegen:
#   filename:  auth-claims.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class AuthClaims(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sub: str
    aud: str
    iat: float
    exp: float
    jti: str
    iss: Literal['flingoos-session-manager']
    device_id: str
    fingerprint: str
