# generated by datamodel-codegen:
#   filename:  auth-token-response.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class AuthTokenResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    authenticated: Literal[True]
    token: str
    expires_at: str
    device_id: str
    fingerprint: str
