# generated by datamodel-codegen:
#   filename:  bridge-command-request.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class Command(Enum):
    ping = 'ping'
    status = 'status'
    audio_start = 'audio_start'
    audio_stop = 'audio_stop'


class BridgeCommandRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: Optional[Command] = None
    timestamp: Optional[float] = None
