# generated by datamodel-codegen:
#   filename:  bridge-command-response.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict


class BridgeCommandResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: bool
    message: str
    timestamp: Optional[float] = None
    session_id: Optional[str] = None
    collectors: Optional[List[str]] = None
    timeout_seconds: Optional[float] = None
    data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
