# generated by datamodel-codegen:
#   filename:  device-proof-request.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class DeviceProofRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    challenge: str
    timestamp: str
