# generated by datamodel-codegen:
#   filename:  device-proof-payload.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class DeviceProofPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    device_id: str
    nonce: str
    timestamp: str
    bridge_version: Optional[str] = None
    hostname: str
    challenge: Optional[str] = None
