# generated by datamodel-codegen:
#   filename:  device-proof-response.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class DeviceProofResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    device_id: Optional[str] = None
    nonce: Optional[str] = None
    proof: Optional[str] = None
    timestamp: Optional[str] = None
    public_key: Optional[str] = None
    hostname: Optional[str] = None
    bridge_version: Optional[str] = None
