# generated by datamodel-codegen:
#   filename:  device-proof-request.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class DeviceProofRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    challenge: Optional[str] = None
    timestamp: Optional[str] = None
