# generated by datamodel-codegen:
#   filename:  error-envelope.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class ErrorCode(Enum):
    BRIDGE_DOWN = 'BRIDGE_DOWN'
    FORGE_TIMEOUT = 'FORGE_TIMEOUT'
    INVALID_SESSION = 'INVALID_SESSION'
    PROCESSING_FAILED = 'PROCESSING_FAILED'


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error_code: ErrorCode
    error_message: str
    correlation_id: str
    timestamp: str
    retry_after: Optional[float] = None
