# generated by datamodel-codegen:
#   filename:  firestore-workflow.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict


class Source(Enum):
    real_firestore = 'real_firestore'
    mock = 'mock'


class Step(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step: float
    action: str
    timestamp: str
    confidence: float
    context: str


class WorkflowData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    summary: str
    duration_seconds: float
    steps: List[Step]
    insights: List[str]
    categories: List[str]
    productivity_score: float
    guide_markdown: str


class ProcessingMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    random_selection: bool
    selected_from_count: float
    retrieval_method: str


class FirestoreWorkflow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    workflow_id: str
    session_id: str
    org_id: str
    processed_at: str
    status: str
    source: Source
    firestore_document_id: str
    firestore_url: str
    firestore_path: str
    workflow_data: WorkflowData
    processing_metadata: ProcessingMetadata
