# generated by datamodel-codegen:
#   filename:  firestore-workflow.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class Source(Enum):
    real_firestore = 'real_firestore'
    mock = 'mock'


class Step(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step: Optional[float] = None
    action: Optional[str] = None
    timestamp: Optional[str] = None
    confidence: Optional[float] = None
    context: Optional[str] = None


class WorkflowData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: Optional[str] = None
    summary: Optional[str] = None
    duration_seconds: Optional[float] = None
    steps: Optional[List[Step]] = None
    insights: Optional[List[str]] = None
    categories: Optional[List[str]] = None
    productivity_score: Optional[float] = None
    guide_markdown: Optional[str] = None


class ProcessingMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    random_selection: Optional[bool] = None
    selected_from_count: Optional[float] = None
    retrieval_method: Optional[str] = None


class FirestoreWorkflow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    workflow_id: Optional[str] = None
    session_id: Optional[str] = None
    org_id: Optional[str] = None
    processed_at: Optional[str] = None
    status: Optional[str] = None
    source: Optional[Source] = None
    firestore_document_id: Optional[str] = None
    firestore_url: Optional[str] = None
    firestore_path: Optional[str] = None
    workflow_data: Optional[WorkflowData] = None
    processing_metadata: Optional[ProcessingMetadata] = None
