# generated by datamodel-codegen:
#   filename:  forge-counters.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class ForgeCounters(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    events_processed: Optional[float] = None
    media_files_processed: Optional[float] = None
    timeline_entries: Optional[float] = None
    llm_tokens_used: Optional[float] = None
    processing_time_seconds: Optional[float] = None
