# generated by datamodel-codegen:
#   filename:  forge-job-response.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict


class Status(Enum):
    completed = 'completed'
    failed = 'failed'
    timeout = 'timeout'
    connection_error = 'connection_error'


class Status1(Enum):
    submitted = 'submitted'
    processing = 'processing'
    completed = 'completed'
    failed = 'failed'


class Type(Enum):
    workflow = 'workflow'
    analysis = 'analysis'


class Artifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    type: Type
    stage: str
    local_path: Optional[str] = None
    gcs_uri: str
    sha256: str
    size_bytes: float
    mime: str
    created_at: str


class Counters(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    events_processed: float
    media_files_processed: float
    timeline_entries: float
    llm_tokens_used: float
    processing_time_seconds: float


class Stage(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    U = 'U'


class Status2(Enum):
    started = 'started'
    completed = 'completed'
    failed = 'failed'


class StageExecution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stage: Stage
    status: Status2
    started_at: str
    completed_at: Optional[str] = None
    error_message: Optional[str] = None
    artifacts_produced: List[str]


class Manifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: str
    processing_id: str
    trigger_hash: str
    session: Dict[str, Any]
    options: Dict[str, Any]
    status: Status1
    created_at: str
    completed_at: Optional[str] = None
    artifacts: List[Artifact]
    counters: Counters
    stage_executions: List[StageExecution]
    content_sha256: str
    error_message: Optional[str] = None
    errors: List


class Status3(Enum):
    submitted = 'submitted'
    processing = 'processing'
    completed = 'completed'
    failed = 'failed'


class ForgeResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    manifest: Manifest
    processing_id: str
    status: Status3
    processing_time_ms: float
    idempotent_reuse: bool


class ForgeJobResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    session_id: str
    processing_time_seconds: float
    firestore_path: Optional[str] = None
    workflow_id: Optional[str] = None
    message: str
    timestamp: str
    error: Optional[str] = None
    forge_response: Optional[ForgeResponse] = None
