# generated by datamodel-codegen:
#   filename:  forge-counters.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ForgeCounters(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    events_processed: float
    media_files_processed: float
    timeline_entries: float
    llm_tokens_used: float
    processing_time_seconds: float
