# generated by datamodel-codegen:
#   filename:  forge-trigger.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: str
    end: str


class Session(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    org_id: str
    device_id: str
    time_range: TimeRange
    timezone: str


class Stage(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    U = 'U'


class Options(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stages: List[Stage]
    media_processing: bool
    llm_enabled: bool


class Visibility(Enum):
    private = 'private'
    public = 'public'


class ForgeTrigger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pipeline_version: str
    config_path: str
    session: Session
    options: Options
    visibility: Visibility
