# generated by datamodel-codegen:
#   filename:  forge-artifact.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class Type(Enum):
    workflow = 'workflow'
    flowchart = 'flowchart'
    analysis = 'analysis'


class ForgeArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    type: Type
    stage: str
    local_path: Optional[str] = None
    gcs_uri: str
    sha256: str
    size_bytes: float
    mime: str
    created_at: str
