# generated by datamodel-codegen:
#   filename:  forge-artifact.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class Type(Enum):
    workflow = 'workflow'
    flowchart = 'flowchart'
    analysis = 'analysis'


class ForgeArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None
    type: Optional[Type] = None
    stage: Optional[str] = None
    local_path: Optional[str] = None
    gcs_uri: Optional[str] = None
    sha256: Optional[str] = None
    size_bytes: Optional[float] = None
    mime: Optional[str] = None
    created_at: Optional[str] = None
