# generated by datamodel-codegen:
#   filename:  forge-job-response.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict


class Status(Enum):
    completed = 'completed'
    failed = 'failed'
    timeout = 'timeout'
    connection_error = 'connection_error'


class Status1(Enum):
    submitted = 'submitted'
    processing = 'processing'
    completed = 'completed'
    failed = 'failed'


class Type(Enum):
    workflow = 'workflow'
    flowchart = 'flowchart'
    analysis = 'analysis'


class Artifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None
    type: Optional[Type] = None
    stage: Optional[str] = None
    local_path: Optional[str] = None
    gcs_uri: Optional[str] = None
    sha256: Optional[str] = None
    size_bytes: Optional[float] = None
    mime: Optional[str] = None
    created_at: Optional[str] = None


class Counters(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    events_processed: Optional[float] = None
    media_files_processed: Optional[float] = None
    timeline_entries: Optional[float] = None
    llm_tokens_used: Optional[float] = None
    processing_time_seconds: Optional[float] = None


class Stage(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    U = 'U'


class Status2(Enum):
    started = 'started'
    completed = 'completed'
    failed = 'failed'


class StageExecution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stage: Optional[Stage] = None
    status: Optional[Status2] = None
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    error_message: Optional[str] = None
    artifacts_produced: Optional[List[str]] = None


class Manifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: Optional[str] = None
    processing_id: Optional[str] = None
    trigger_hash: Optional[str] = None
    session: Optional[Dict[str, Any]] = None
    options: Optional[Dict[str, Any]] = None
    status: Optional[Status1] = None
    created_at: Optional[str] = None
    completed_at: Optional[str] = None
    artifacts: Optional[List[Artifact]] = None
    counters: Optional[Counters] = None
    stage_executions: Optional[List[StageExecution]] = None
    content_sha256: Optional[str] = None
    error_message: Optional[str] = None
    errors: Optional[List] = None


class Status3(Enum):
    submitted = 'submitted'
    processing = 'processing'
    completed = 'completed'
    failed = 'failed'


class ForgeResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    manifest: Optional[Manifest] = None
    processing_id: Optional[str] = None
    status: Optional[Status3] = None
    processing_time_ms: Optional[float] = None
    idempotent_reuse: Optional[bool] = None


class ForgeJobResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Optional[Status] = None
    session_id: Optional[str] = None
    processing_time_seconds: Optional[float] = None
    firestore_path: Optional[str] = None
    workflow_id: Optional[str] = None
    message: Optional[str] = None
    timestamp: Optional[str] = None
    error: Optional[str] = None
    forge_response: Optional[ForgeResponse] = None
