# generated by datamodel-codegen:
#   filename:  forge-trigger.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: Optional[str] = None
    end: Optional[str] = None


class Session(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    org_id: Optional[str] = None
    device_id: Optional[str] = None
    time_range: Optional[TimeRange] = None
    timezone: Optional[str] = None


class Stage(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    U = 'U'


class Options(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stages: Optional[List[Stage]] = None
    media_processing: Optional[bool] = None
    llm_enabled: Optional[bool] = None
    include_flowchart: Optional[bool] = None


class Visibility(Enum):
    private = 'private'
    public = 'public'


class ForgeTrigger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pipeline_version: Optional[str] = None
    config_path: Optional[str] = None
    session: Optional[Session] = None
    options: Optional[Options] = None
    visibility: Optional[Visibility] = None
