# generated by datamodel-codegen:
#   filename:  index.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from typing import Any

from pydantic import Field, RootModel


class FlingoosSharedSchemasIndex(RootModel[Any]):
    root: Any = Field(..., title='Flingoos Shared Schemas Index')
