# generated by datamodel-codegen:
#   filename:  index.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import Field, RootModel


class FlingoosSharedSchemasIndex(RootModel[Optional[Any]]):
    root: Optional[Any] = Field(None, title='Flingoos Shared Schemas Index')
