# generated by datamodel-codegen:
#   filename:  job-progress.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, confloat


class CurrentStage(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    U = 'U'


class StagesCompletedEnum(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    U = 'U'


class JobProgress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    processing_id: str
    progress_percent: confloat(ge=0.0, le=100.0)
    current_stage: CurrentStage
    stage_name: str
    stages_completed: List[StagesCompletedEnum]
    stages_total: float
    estimated_completion: Optional[str] = None
    elapsed_seconds: float
    stage_durations: Dict[str, float]
