# generated by datamodel-codegen:
#   filename:  job-progress.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, confloat


class CurrentStage(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    U = 'U'


class StagesCompletedEnum(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    U = 'U'


class JobProgress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    processing_id: Optional[str] = None
    progress_percent: Optional[confloat(ge=0.0, le=100.0)] = None
    current_stage: Optional[CurrentStage] = None
    stage_name: Optional[str] = None
    stages_completed: Optional[List[StagesCompletedEnum]] = None
    stages_total: Optional[float] = None
    estimated_completion: Optional[str] = None
    elapsed_seconds: Optional[float] = None
    stage_durations: Optional[Dict[str, float]] = None
