# generated by datamodel-codegen:
#   filename:  session-start-response.json
#   timestamp: 2025-09-08T11:25:31+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class Status(Enum):
    recording = 'recording'
    processing = 'processing'
    completed = 'completed'
    failed = 'failed'


class SessionStartResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: bool
    session_id: Optional[str] = None
    status: Optional[Status] = None
    message: Optional[str] = None
    error: Optional[str] = None
