# generated by datamodel-codegen:
#   filename:  session-event.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SessionEvent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session_started'] = 'session_started'
    session_id: Optional[str] = None
    message: Optional[str] = None


class SessionEvent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session_stopped'] = 'session_stopped'
    session_id: Optional[str] = None
    message: Optional[str] = None


class SessionEvent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session_error'] = 'session_error'
    error: Optional[str] = None


class CompletedStep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: Optional[str] = None
    status: Optional[str] = None


class SessionEvent4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['upload_status'] = 'upload_status'
    current_step: Optional[str] = None
    completed_steps: Optional[List[CompletedStep]] = None
    total_steps: Optional[float] = None


class SessionEvent5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['workflow_ready'] = 'workflow_ready'
    workflow_id: Optional[str] = None
    title: Optional[str] = None
    summary: Optional[str] = None
    steps: Optional[List] = None
    guide_markdown: Optional[str] = None


class SessionEvent6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['upload_complete'] = 'upload_complete'
    message: Optional[str] = None
    has_workflow: Optional[bool] = None


class SessionEvent(
    RootModel[
        Optional[
            Union[
                SessionEvent1,
                SessionEvent2,
                SessionEvent3,
                SessionEvent4,
                SessionEvent5,
                SessionEvent6,
            ]
        ]
    ]
):
    root: Optional[
        Union[
            SessionEvent1,
            SessionEvent2,
            SessionEvent3,
            SessionEvent4,
            SessionEvent5,
            SessionEvent6,
        ]
    ] = Field(
        None,
        description='WebSocket session event messages for real-time UI updates',
        title='Session Event',
    )
