# generated by datamodel-codegen:
#   filename:  session-event.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from typing import List, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SessionEvent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session_started']
    session_id: str
    message: str


class SessionEvent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session_stopped']
    session_id: str
    message: str


class SessionEvent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session_error']
    error: str


class CompletedStep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: str
    status: str


class SessionEvent4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['upload_status']
    current_step: str
    completed_steps: List[CompletedStep]
    total_steps: float


class SessionEvent5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['workflow_ready']
    workflow_id: str
    title: str
    summary: str
    steps: List
    guide_markdown: str


class SessionEvent6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['upload_complete']
    message: str
    has_workflow: bool


class SessionEvent(
    RootModel[
        Union[
            SessionEvent1,
            SessionEvent2,
            SessionEvent3,
            SessionEvent4,
            SessionEvent5,
            SessionEvent6,
        ]
    ]
):
    root: Union[
        SessionEvent1,
        SessionEvent2,
        SessionEvent3,
        SessionEvent4,
        SessionEvent5,
        SessionEvent6,
    ] = Field(
        ...,
        description='WebSocket session event messages for real-time UI updates',
        title='Session Event',
    )
