# generated by datamodel-codegen:
#   filename:  session-status-response.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class SessionStatusResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: bool
    bridge_connected: Optional[bool] = None
    active_sessions: Optional[float] = None
    sessions: Optional[List[str]] = None
    workflow_results: Optional[float] = None
