# generated by datamodel-codegen:
#   filename:  session-internal-state.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict


class Status(Enum):
    recording = 'recording'
    processing = 'processing'
    completed = 'completed'
    failed = 'failed'


class SessionInternalState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str
    start_time: Optional[str] = None
    stop_time: Optional[str] = None
    status: Status
    bridge_response: Optional[Dict[str, Any]] = None
    bridge_stop_response: Optional[Dict[str, Any]] = None
    workflow_ready: Optional[bool] = None
    processing_id: Optional[str] = None
    firestore_path: Optional[str] = None
    workflow_id: Optional[str] = None
    processing_time_seconds: Optional[float] = None
    error_message: Optional[str] = None
