# generated by datamodel-codegen:
#   filename:  stage-execution.json
#   timestamp: 2025-09-08T13:42:51+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class Stage(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    U = 'U'


class Status(Enum):
    started = 'started'
    completed = 'completed'
    failed = 'failed'


class StageExecution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stage: Stage
    status: Status
    started_at: str
    completed_at: Optional[str] = None
    error_message: Optional[str] = None
    artifacts_produced: List[str]
