# generated by datamodel-codegen:
#   filename:  standard-error-response.json
#   timestamp: 2025-09-08T12:19:59+00:00

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict


class StandardErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[False] = False
    error: Optional[str] = None
